### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by YuvaraniThambidurai** [OSU-SRLab/MANTIS#46] opened 2019-07-22 06:10 UTC
Hi,
      I have tried many times running MANTIS but it is taking lot of time in the first step (Getting repeat counts for repeat units (K-mer)... ) and after two or three hours I receive the message as broken pipe. And I generated the BED file in the specified format using Repeatfinder. Could u help me in resolving the issue?

**Comment by rbonneville** [comment] 2019-07-22 15:03
Duplicate of #47

**Closed by rbonneville** 2019-07-22 15:03 UTC
